### PR TITLE
Enable downstream build only in typetools version

### PR DESCRIPTION
**Pull request by topnessman**

### CODE REVIEW

**Comment by mernst** [comment]
Tony, I'm not clear what the typetools fork of this repository is.  Would it be better to make any change that is specific to that fork, in that fork?

**Comment by topnessman** [comment]
Should I make a PR against typetools/plume-lib?

**Comment by mernst** [comment]
What is the point of typetools/plume-lib?  Other libraries there are annotated versions of the upstream library.  But mernst/plume-lib is already annotated.

**Comment by mernst** [comment]
I'm closing this pull request because the question that I asked on July 24 and July 25 has not been answered.

**Pull request closed without merging**
